# Generated by Django 3.1.4 on 2021-04-24 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20210424_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_format',
            field=models.IntegerField(choices=[(0, 'Print'), (1, 'Ebook'), (2, 'Audiobook')], default=0),
        ),
    ]
